### ISSUE TITLE
SSL home assistant error 

### ISSUE THREAD

**Issue by jhopkins213** [Shaegi/Homeassistant-WLED-Card#5]
Fallowed your instructions but I think it's because I'm using https for home assistant I no longer get the error but I get this isnted when I inspect the page in chrome
wled_control.js:20 Mixed Content: The page at 'https://username.duckdns.org:8123/lovelace/hidden_view' was loaded over HTTPS, but requested an insecure resource 'http://192.168.86.223/win'. This request has been blocked; the content must be served over HTTPS.

**Comment by Shaegi** [comment]
It seems like mixed content is blocked by the browser to insure HTTPS is secure. Since WLED doesn't serve on HTTPS you can't request it over HTTP as you mentioned. 
It seems that you can't bypass it other than upgrading the source (WLED) to be served by HTTPS. 
Reference: 
https://stackoverflow.com/questions/37043719/how-can-i-allow-mixed-contents-http-with-https-using-content-security-policy-m

Since I have to fetch the initial state via HTTP I don't think I can solve your problem within this libary. The only solve for this would be having WLED to be served over HTTPS. Therefore I'd suggest that you open an issue on the WLED repo. 

If you have any other suggestions resolving the issue on my end, let me know.
